from enum import StrEnum


class SalesOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    CONFIRMED = "CONFIRMED"
    FULFILLED = "FULFILLED"
    CANCELLED = "CANCELLED"


class ProductStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DISCONTINUED = "DISCONTINUED"


class InventoryStatus(StrEnum):
    NORMAL = "NORMAL"
    LOW_STOCK = "LOW_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"


class MovementType(StrEnum):
    IN = "IN"
    OUT = "OUT"


class ReceivableStatus(StrEnum):
    UNPAID = "UNPAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"


class PayableStatus(StrEnum):
    UNPAID = "UNPAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"


class EmployeeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class TaskStatus(StrEnum):
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING_REVIEW = "PENDING_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED_FOR_EXECUTION = "APPROVED_FOR_EXECUTION"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    CANCELLED = "CANCELLED"


class RecommendationStatus(StrEnum):
    SUGGESTED = "SUGGESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class SubmissionStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    WITHDRAWN = "WITHDRAWN"


class ExecutionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class TaskType(StrEnum):
    RECEIVE = "RECEIVE"
    PUTAWAY = "PUTAWAY"
    PICK = "PICK"
    PACK = "PACK"
    STOCK_IN = "STOCK_IN"
    STOCK_OUT = "STOCK_OUT"
    TRANSFER = "TRANSFER"
    INVENTORY_COUNT = "INVENTORY_COUNT"


class ActorType(StrEnum):
    EMPLOYEE = "EMPLOYEE"
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"


class OrderItemStatus(StrEnum):
    PENDING = "PENDING"
    FULFILLED = "FULFILLED"
    CANCELLED = "CANCELLED"


class OutboundStatus(StrEnum):
    PENDING_OUTBOUND = "PENDING_OUTBOUND"
    RESERVED = "RESERVED"
    PICKING = "PICKING"
    READY_TO_SHIP = "READY_TO_SHIP"
    SHIPPED = "SHIPPED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReservationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONSUMED = "CONSUMED"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class PurchaseOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    ORDERED = "ORDERED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"


class ReceiptStatus(StrEnum):
    PENDING_RECEIPT = "PENDING_RECEIPT"
    RECEIVING = "RECEIVING"
    PENDING_INSPECTION = "PENDING_INSPECTION"
    INSPECTING = "INSPECTING"
    INSPECTED = "INSPECTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReturnDirection(StrEnum):
    FROM_CUSTOMER = "FROM_CUSTOMER"
    TO_SUPPLIER = "TO_SUPPLIER"


class ReturnStatus(StrEnum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    PENDING_OUTBOUND = "PENDING_OUTBOUND"
    IN_TRANSIT = "IN_TRANSIT"
    PENDING_RECEIPT = "PENDING_RECEIPT"
    PENDING_INSPECTION = "PENDING_INSPECTION"
    RECEIVED = "RECEIVED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class TransferStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_OUTBOUND = "PENDING_OUTBOUND"
    PICKING = "PICKING"
    IN_TRANSIT = "IN_TRANSIT"
    PENDING_RECEIPT = "PENDING_RECEIPT"
    RECEIVED = "RECEIVED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class StockStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    PICKING = "PICKING"
    FROZEN = "FROZEN"
    QUARANTINED = "QUARANTINED"
    DEFECTIVE = "DEFECTIVE"
